name: Despliegue con Surge.sh

on:
  push:
    branches:
      - main # El despliegue se activar치 en cada push a la rama 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest # Ejecutar en un entorno Linux

    steps:
    - name: Checkout del c칩digo
      uses: actions/checkout@v4 # Obtener el c칩digo del repositorio

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Puedes especificar la versi칩n de Node.js que prefieras

    - name: Instalar Surge CLI
      run: npm install -g surge # Instalar Surge CLI globalmente

    - name: Desplegar en Surge.sh
      run: surge --project ./ --domain ${{ secrets.SURGE_DOMAIN }}
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
